on:  
  push:  
    branches:  
      - master  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      # Check out the repository code
      - uses: actions/checkout@v3  

      # Log in to Docker Hub
      - name: "Log in to Docker Hub"  
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      # Build the Docker image
      - name: "Building Docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage .

      # Push the image to Docker Hub
      - name: "Pushing Docker image to Docker Hub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage
