on:  
  push:  
    branches:  
      - master  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      # Step 1: Check out the repository code
      - uses: actions/checkout@v3  

      # Step 2: Log in to Docker Hub
      - name: "Login to Docker Hub"
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build the Docker image
      - name: "Building Docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage .

      # Step 4: Push the Docker image to Docker Hub
      - name: "Pushing Docker image to Docker Hub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myimage
