favoritesongs:
  - 'songe #1'
  - 'songe #2'
  - 'songe #3'

favoritesongs: ['songe #1', 'songe #1']

characteristic:
  age:25
  height:170
  skincolor:''


on:
  push:
 
    branches:
      - master



jobs:
  build:
   
    runs-on: ubuntu-latest 

    steps:
      - name: "testing github actions"
        run: pwd
      - name: "testing printing"
        run: echo ahmed


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

      - name: "before printing the folder containts"
        run: ls

      - uses: actions/checkout@v3

      - name: "after printing the folder containts"
        run: ls

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ali11 --password dckr_pat_53484obn9zPM_cmRsBftedTlw5w


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
       

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME}} --password ${{ secrets.DOCKER_TOKEN }}
      - name: " building docker "
        run: docker build -t ${{ secrets.DOCKER_USERNAME}}/docker-image-creation .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKER_USERNAME}}/docker-image-creation
        
task

